# Generated by Django 4.1.5 on 2024-01-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='uploaded_videos')),
                ('output_file', models.FileField(blank=True, null=True, upload_to='output_videos')),
            ],
        ),
    ]
