# Generated by Django 4.1.5 on 2024-01-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suspicious_activity_detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='output_file',
            field=models.FileField(null=True, upload_to='output_videos', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(null=True, upload_to='uploaded_videos', verbose_name=''),
        ),
    ]
